### PR TITLE
A slightly different version of #102

### PR DESCRIPTION
**Pull request by dinosaure**
This is a slightly different version of #102 which keeps `HAS_SECURE_GETENV` to be able to produce an unikernel without Unix syscalls (/cc @hannesm).

### CODE REVIEW

**Comment by dinosaure** [comment]
For a more complete response, OCaml has [such code](https://github.com/ocaml/ocaml/blob/35af4cddfd31129391f904167236270a004037f8/runtime/unix.c#L407-L421) where, without `HAS_SECURE_GETENV`, we bring some Unix _syscalls_.

**Comment by dinosaure** [comment]
I can confirm that this version can compile on OpenBSD 7 :tada:.

**Comment by hannesm** [comment]
Hmm, I'm not sure this is the right fix. OCaml's configure detects the presence of `secure_getenv` fine on FreeBSD and OpenBSD (which is defined in nolibc/stdlib.h). Only on Linux, there is an issue in config.log:
```
configure:11596: checking for secure_getenv
configure:11596: cc -ffreestanding -fstack-protector-strong -nostdinc -mstack-protector-guard=global -isystem /home/administrator/.opam/4.13.
1/lib/pkgconfig/../../include/solo5-bindings-hvt/crt -I/home/administrator/.opam/4.13.1/lib/pkgconfig/../../include/solo5-bindings-hvt/solo5 
-I/home/administrator/ocaml-freestanding/nolibc/include -include _freestanding/overrides.h -I/home/administrator/ocaml-freestanding/openlibm/
include -I/home/administrator/ocaml-freestanding/openlibm/src -nostdlib -o conftest  -D_GNU_SOURCE -ffreestanding -fstack-protector-strong -n
ostdinc -mstack-protector-guard=global -isystem /home/administrator/.opam/4.13.1/lib/pkgconfig/../../include/solo5-bindings-hvt/crt -I/home/a
dministrator/.opam/4.13.1/lib/pkgconfig/../../include/solo5-bindings-hvt/solo5 -I/home/administrator/ocaml-freestanding/nolibc/include -inclu
de _freestanding/overrides.h -I/home/administrator/ocaml-freestanding/openlibm/include -I/home/administrator/ocaml-freestanding/openlibm/src 
-nostdlib -z max-page-size=0x1000 -static  -T /home/administrator/.opam/4.13.1/lib/pkgconfig/../../lib/solo5-bindings-hvt/solo5_hvt.lds /home
/administrator/.opam/4.13.1/lib/pkgconfig/../../lib/solo5-bindings-hvt/solo5_hvt.o  -L/home/administrator/ocaml-freestanding/openlibm -L/home
/administrator/ocaml-freestanding/nolibc conftest.c -lopenlibm -lnolibc >&5
/usr/bin/ld: /home/administrator/ocaml-freestanding/nolibc/libnolibc.a(vfprintf.o): in function `fmt_fp':
vfprintf.c:(.text+0x348): undefined reference to `__signbitl'
/usr/bin/ld: vfprintf.c:(.text+0x389): undefined reference to `__isfinitel'
/usr/bin/ld: vfprintf.c:(.text+0x4ec): undefined reference to `frexpl'
collect2: error: ld returned 1 exit status
```

**Comment by dinosaure** [comment]
Ok I will do a end-to-end test with #102 and confirm that your PR works 👍 .

**Pull request closed without merging**
