### PR TITLE
Support OCaml 4.05

### PR DESCRIPTION
**Pull request by mato**
Straightforward apart from hack in configure.sh to disable the code in
afl.c by defining `__ANDROID__` for this module only.

### CODE REVIEW

**Comment by mato** [comment]
@hannesm OK with this change as a more minimal variation on #20?

**Comment by mato** [comment]
Travis seems happy so I'm going to merge this rather than #20, so as to get a release out ASAP.

**Comment by avsm** [comment]
I prefer the change of defining __ANDROID__ rather than stubbing out shm.  I think this needs improving in upstream OCaml as well -- the afl.c should be using a `HAS_SHM` feature check rather than the Windows/Android check it currently has. cc @stedolan

**Comment by mato** [comment]
I've verified that the mirage-skeleton `tutorial/hello` and `device-usage/network` build and run OK with this change (using OCaml 4.05.0 and solo5-kernel-ukvm).

Note that there seem to be other problems further down the Mirage stack that may be 4.05 related as a HTTP unikernel does not build for me (fails to install dependencies at mirage configure time), but that is unrelated to this change.

**Comment by hannesm** [comment]
thx @mato -- sorry was travelling and couldn't respond earlier

**Comment by hannesm** [comment]
just FYI for 4.06 we won't need the `-D__ANDROID__` anymore, since https://github.com/ocaml/ocaml/pull/1278 got merged

**Comment by mato** [comment]
@hannesm Is that likely to also land in a 4.05.x point release?

**Comment by hannesm** [comment]
@mato I don't know (neither whether a 4.05.x is planned, neither how to propose merging changes into the 4.05.releng branch)

**Comment by hannesm** [comment]
@mato but we should be future-proof since we don't run configure and don't define `HAS_SYS_SHM_H` in our `s.h`.

**Comment by avsm** [comment]
There's no 4.05.1 point release planned at present, so this will just be in 4.06.0

**Pull request merged**
