### PR TITLE
declare to be freestanding

### PR DESCRIPTION
**Pull request by hannesm**
see https://github.com/mirage/mirage-platform/pull/178 and https://github.com/mirage/mirage/issues/660 - would be great to have this included before a release (note: i haven't tested this change) -- sorry @mato, I see you already did a release...

### CODE REVIEW

**Comment by mato** [comment]
Can you provide a unikernel to test this with? I can make an 0.2.1 release easily enough...

**Comment by hannesm** [comment]
I'm just building mirage-skeleton for virtio with this change.. let you
know about the results

**Comment by hannesm** [comment]
(this PR won't work with 4.03, the change has to be guarded (and only applied to 4.04+))

**Comment by hannesm** [comment]
updated the patch (moved to `configure.sh`, and only set os_type to freestanding on 4.04+.

Testing unikernel (derived from console):

config.ml:
```OCaml
open Mirage

let main =
  foreign
    ~packages:[package "duration"]
    "Unikernel.Main" (console @-> time @-> job)

let () =
  register "console" [main $ default_console $ default_time ]
```

unikernel.ml
```OCaml
open Lwt.Infix

module Main (C: Mirage_types_lwt.CONSOLE) (Time: Mirage_types_lwt.TIME) = struct

  let start c _time =
    let rec loop = function
      | 0 -> Lwt.return_unit
      | n ->
        C.log c ("hello on " ^ Sys.os_type) >>= fun () ->
        Time.sleep_ns (Duration.of_sec 1) >>= fun () ->
        C.log c "world" >>= fun () ->
        loop (pred n)
    in
    loop 4

end
```

**Comment by mato** [comment]
LGTM, waiting for Travis.

**Comment by mato** [comment]
Have cut a v0.2.1 release with this change and updated the mirageos-3-beta PR.

**Pull request merged**
